spring:
  application:
    name: eureka-server
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 9000

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


